name       : kde-gtk-config
version    : 5.24.3
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.3/kde-gtk-config-5.24.3.tar.xz : fb4bcd30c93e15962153e81ca218f03465f02d1d2d011f267bb96946869ba05c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
optimize   : lto
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Svg)
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdecoration-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - sassc
rundeps    :
    - gsettings-desktop-schemas
    - xsettingsd
setup      : |
    %patch -p1 -i $pkgfiles/0002-Use-explicit-path-of-the-gtk-module.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
