name       : kde-gtk-config
version    : 5.11.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kde-gtk-config-5.11.1.tar.xz : 549d0828a5bdc6e46c9d08fd0c2b03c2aaada8b64ffbee39162aed2673e3cba9
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-explicit-path-of-the-gtk-module.patch
    %patch -p1 < $pkgfiles/0001-Revert-Make-the-kde-gtk-config-kcm-better-at-checkin.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
