name       : kde-gtk-config
version    : 5.23.5
release    : 76
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/kde-gtk-config-5.23.5.tar.xz : 178e5f342a0a95043c8aa0cf0c7db23a0003b0d971a5aadc2400a4bf85ef1893
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
optimize   : lto
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Svg)
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdecoration-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - sassc
rundeps    :
    - gsettings-desktop-schemas
    - xsettingsd
setup      : |
    %patch -p1 -i $pkgfiles/0002-Use-explicit-path-of-the-gtk-module.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
