name       : kde-gtk-config
version    : 5.18.4.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.4/kde-gtk-config-5.18.4.1.tar.xz : 20dea1d6b9f0ba7c9987dcdd61aa3cfc7b27968b393f600e29e00ae561179c09
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
rundeps    :
    - gsettings-desktop-schemas
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
