name       : kde-gtk-config
version    : 5.16.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.2/kde-gtk-config-5.16.2.tar.xz : b1c3c2fd62bcb0bb08a1966843be28b829d4cc43931aad02336f452adc5b2793
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - gsettings-desktop-schemas
    - karchive-devel
    - kcmutils-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
rundeps    :
    - gsettings-desktop-schemas
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Use-explicit-path-of-the-gtk-module.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
