name       : kde-gtk-config
version    : 5.10.1
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kde-gtk-config-5.10.1.tar.xz : 896f88a31a2d02adf3a28dea0976ff90b91c9ec4cf4956c9b653338cf9cd1920
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
