name       : kde-gtk-config
version    : 5.20.2
release    : 57
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.2/kde-gtk-config-5.20.2.tar.xz : 50b73d1d7fb15c99919b841fdc3e663c454ea0a8dca97b4b876581499e9db7d4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdecoration-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - sassc
rundeps    :
    - gsettings-desktop-schemas
setup      : |
    %patch -p1 -i $pkgfiles/0002-Use-explicit-path-of-the-gtk-module.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
