name       : kde-gtk-config
version    : 5.27.7
release    : 89
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/kde-gtk-config-5.27.7.tar.xz : ae2a1e468f4132a8efcf61818847d453e73f8b7010d900a6a1406fd7de901c8f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
optimize   : lto
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Svg)
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdecoration-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kguiaddons-devel
    - kwindowsystem-devel
    - sassc
rundeps    :
    - gsettings-desktop-schemas
    - xsettingsd
setup      : |
    %patch -p1 -i $pkgfiles/0002-Use-explicit-path-of-the-gtk-module.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
