name       : kde-gtk-config
version    : 5.19.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/kde-gtk-config-5.19.2.tar.xz : 02011dd01c045abe7b086a6aa844b267a907295591cd92987309f3b9169a5b9c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gsettings-desktop-schemas
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kguiaddons-devel
rundeps    :
    - gsettings-desktop-schemas
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
