name       : kde-gtk-config
version    : 5.10.5
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kde-gtk-config-5.10.5.tar.xz : a5bedaa880d416a8ab259c59dc84b4086a1cb8582d95d8632d79c3e9a746b8a8
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(xcursor)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-explicit-path-of-the-gtk-module.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
